version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vkr
      POSTGRES_PASSWORD: vkr123
      POSTGRES_DB: vkr
    ports:
      - 5432:5432
  vkr:
    image: vika2108991/vkr
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 5000:5000
    command: flask run --host=0.0.0.0

volumes:
  data:
